In [1]:
# explore glove word emebddings

In [21]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

In [14]:
# function to load glove vectors from file
def load_glove(file_path):
    file_object  = open(file_path, "r") 
    model = {} 
    for l in file_object:
        line = l.split()
        word = line[0]
        value = np.array([float(val) for val in line[1:]])
        model[word] = value
    return model

In [22]:
file_with_path = "../data/embeddings/glove.6B.50d.txt"
glove = load_glove(file_with_path)

In [31]:
glove['python'].reshape(1, -1)

array([[ 0.5897  , -0.55043 , -1.0106  ,  0.41226 ,  0.57348 ,  0.23464 ,
        -0.35773 , -1.78    ,  0.10745 ,  0.74913 ,  0.45013 ,  1.0351  ,
         0.48348 ,  0.47954 ,  0.51908 , -0.15053 ,  0.32474 ,  1.0789  ,
        -0.90894 ,  0.42943 , -0.56388 ,  0.69961 ,  0.13501 ,  0.16557 ,
        -0.063592,  0.35435 ,  0.42819 ,  0.1536  , -0.47018 , -1.0935  ,
         1.361   , -0.80821 , -0.674   ,  1.2606  ,  0.29554 ,  1.0835  ,
         0.2444  , -1.1877  , -0.60203 , -0.068315,  0.66256 ,  0.45336 ,
        -1.0178  ,  0.68267 , -0.20788 , -0.73393 ,  1.2597  ,  0.15425 ,
        -0.93256 , -0.15025 ]])

In [36]:
# calulclate cosine similarity (import from sklearn for example)
cosine_similarity(glove['fast'].reshape(1, -1), glove['speed'].reshape(1, -1))

array([[0.75120749]])

In [46]:
# embeddings operations -> classic queen - woman + man =  king 
predicted_king = glove['queen'] - glove['woman'] + glove['man']
actual_king = glove['king']

cosine_similarity(actual_king.reshape(1, -1), predicted_king.reshape(1, -1)) # quite close

array([[0.85888392]])

# calculate own embeddings with CBOW (alternative would be skipgrams)